#! /bin/bash


sudo apt install xinit #xdm

### install xmonad, a Haskell-based window manager, and common utilities for it ###
sudo apt update
sudo apt install xmonad libghc-xmonad-contrib-dev libghc-xmonad-dev suckless-tools
#sudo update-alternatives --install /usr/bin/x-session-manager x-session-manager /usr/bin/xmonad 60
### end install of xmonad, etc. ###
cp {.xinitrc,.bash_profile} ~/
